from .xml_objects import (
    PotObject,
    PotLidObject,
    TrayObject,
    BreadObject,
    ToasterObject,
    TableObject,
    MicrowaveObject,
    NailObject,
    ToolboxObject,
    DoorObject,
    WallObject,
    BrushObject,
    ParticleObject,
    StoveObject,
    LadleObject,
    HammerObject,
    TargetObject,
    LaneObject,
    LineObject,
    CartObject,
    PegboardObject,
    SocketObject,
    TrashCanObject,
    PowerSwitchObject,
)
# from .shelf import ShelfObject
